config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'home#index'
    get 'index',                    to: 'home#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :categories,          only: [:show]
    resources :products,            only: [:show] do
      collection do
        get 'search'
      end
    end
    get   'cart',                   to: 'orders#edit'
    patch 'cart',                   to: 'orders#update'
    resources :line_items,          only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/product_decorator.rb
module Spree::ProductDecorator
  def self.prepended(base)
    # default_price, imagesを含める
    base.scope :includes_price_and_image, -> { base.includes(master: [:default_price, :images]) }
    # Variant配下のOptionValueを取得して、OptionValueのnameがURLクエリと一致する商品を取得
    base.scope :search_option_value, -> (option_value) { base.includes(variants: :option_values).where(spree_option_values: { name: option_value }) }
    # 商品の並び替え
    base.scope :new_products, -> { base.order(available_on: "desc") }
    base.scope :old_products, -> { base.order(available_on: "asc") }
    base.scope :sort_types, -> (sort) {
      case sort
      when "NEW_PRODUCTS"
        reorder(nil).new_products
      when "OLD_PRODUCTS"
        reorder(nil).old_products
      when "LOW_PRICE"
        unscope(:order).ascend_by_master_price
      when "HIGH_PRICE"
        unscope(:order).descend_by_master_price
      end
    }
    # 検索機能
    base.scope :search_option, -> (search_word) { where('name LIKE ? OR description LIKE ?', "%#{sanitize_sql_like(search_word)}%", "%#{sanitize_sql_like(search_word)}%") if search_word.present? }
  end

  # 関連商品の取得（distinct→product自身を関連商品として表示しない）
  def related_products
    Spree::Product.in_taxons(taxons).where.not(id: id).distinct
  end

  Spree::Product.prepend self
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  helper_method :products_count_option

  def show
    @categories = Spree::Taxonomy.all.includes(:root)
    @taxon      = Spree::Taxon.find(params[:id])
    @colors     = Spree::OptionType.find_by(presentation: "Color").option_values
    @sizes      = Spree::OptionType.find_by(presentation: "Size").option_values
    @products   = filtered_products.sort_types(params[:sort])
  end

  private

  def products_count_option(option_value)
    Spree::Product.in_taxon(@taxon).search_option_value(option_value).count
  end

  def filtered_products
    scope = @taxon.all_products.includes_price_and_image
    params[:option_value].presence || scope.search_option_value(params[:option_value])
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  MAX_NEW_PRODUCTS_IMAGE = 8

  def index
    @new_products = Spree::Product.includes(master: [:default_price, :images]).order(available_on: "DESC").limit(MAX_NEW_PRODUCTS_IMAGE)
  end
end

app/controllers/potepan/line_items_controller.rb
class Potepan::LineItemsController < ApplicationController
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store

  # https://github.com/solidusio/solidus/blob/master/frontend/app/controllers/spree/orders_controller.rb
  def create
    order = current_order(create_order_if_necessary: true)
    authorize! :update, order, cookies.signed[:guest_token]
    variant  = Spree::Variant.find(params[:variant_id])
    quantity = params[:quantity].present? ? params[:quantity].to_i : 1

    # カートに入る数の最大値を設定、それ以上の数値はエラー
    if !quantity.between?(1, 2_147_483_647)
      order.errors.add(:base, t('spree.please_enter_reasonable_quantity'))
    end

    # カートのアップデート時にエラーが起こった場合に,エラ-メッセージを返す
    begin
      @line_item = order.contents.add(variant, quantity)
    rescue ActiveRecord::RecordInvalid => e
      order.errors.add(:base, e.record.errors.full_messages.join(", "))
    end

    if order.errors.any?
      flash[:error] = @order.errors.full_messages.join(", ")
      redirect_back_or_default(potepan_index_path)
      return
    else
      redirect_to potepan_cart_path
    end
  end

  def destroy
    item = Spree::LineItem.find(params[:id])
    item.order.contents.remove_line_item(item)
    redirect_to potepan_cart_path
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store

  # https://github.com/solidusio/solidus/blob/master/frontend/app/controllers/spree/orders_controller.rb
  def edit
    @order = current_order || Spree::Order.incomplete.find_or_initialize_by(guest_token: cookies.signed[:guest_token])
  end

  def update
    @order = Spree::Order.find_by(number: params[:number])
    @order.contents.update_cart(order_params)
    redirect_to potepan_cart_path
  end

  private

  def order_params
    params.require(:order).permit(line_items_attributes: [:id, :quantity])
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_NUMBER_OF_RELATED_PRODUCTS = 4

  def show
    @product          = Spree::Product.find(params[:id])
    @related_products = @product.related_products.includes(master: [:default_price, :images]).limit(MAX_NUMBER_OF_RELATED_PRODUCTS)
    @line_item = Spree::LineItem.new
    if @product.empty_option_values?
      @variant = @product.master
      @value_array = []
    else
      @value_array = @product.variants.map { |val| [val.options_text, "#{val.id}"] }
    end
  end

  def search
    @search = params[:search]
    @products = Spree::Product.includes_price_and_image.search_option(@search)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # タイトルの共通化
  def full_title(page_title)
    base_title = "BIGBAG store"
    if page_title.blank?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<!-- COPY RIGHT -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.zone.now.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer_logos_images.html.erb
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
          <li><span><a data-toggle="modal" href='.login-modal'>ログイン</a><small>or</small><a data-toggle="modal" href='#signup'>新規登録</a></span></li>
            <li class="dropdown searchBox">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <%= form_with(url: search_potepan_products_path, id: "form01", method: "get", enforce_utf8: false) do %>
                    <span class="input-group">
                    <%= text_field_tag :search, "", class: "form-control", placeholder: "Search…", aria_describedby:"basic-addon2" %>
                    <button><span class="input-group-addon" id="basic-addon2" onclick="submit(this.form)">検索</span></button>
                  <% end %>
                  </span>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="cart-page.html" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <%= link_to image_tag("logo.png"), potepan_index_path, class: "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", potepan_index_path %></li>
          <li class="dropdown megaDropMenu active">
            <%= link_to "Shop", potepan_category_path(1) %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_login_model.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade login-modal" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">ログイン</h3>
      </div>
      <div class="modal-body">
        <form action="login-" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">メールアドレス</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">パスワード</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> 記憶しておく
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">ログイン</button>
          <a href="lost-password.html" class="btn btn-link btn-block">パスワードをお忘れの方</a>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_signup_model.html.erb
<!-- SIGN UP MODAL -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">新規登録</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">メールアドレス</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">パスワード</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">パスワード（確認用）</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
        　</div>
          <button type="submit" class="btn btn-primary btn-block">登録する</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/potepan/categories/_categories_sidebar.html.erb
<div class="panel panel-default">
  <div class="panel-heading">商品カテゴリー</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% categories.each do |category| %>
          <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#category-<%= category.id %>"><%= category.name %>
              <i class="fa fa-plus"></i>
            </a>
            <ul id="category-<%= category.id %>" class="collapse collapseItem">
              <% category.root.leaves.each do |leaf| %>
                <li>
                  <%= link_to potepan_category_path(leaf.id) do %>
                    <i class="fa fa-caret-right" aria-hidden="true"></i><%= leaf.name %><span>(<%= leaf.products.count %>)</span>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/_filter_by_color.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <% colors.each do |color| %>
        <li class="filter-by-color">
          <%= link_to potepan_category_path(color: color.name) do %>
            <%= color.name %><span>(<%= products_count_option(color.name) %>)</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/categories/_filter_by_size.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
    <div class="panel-body">
      <% sizes.each do |size| %>
        <ul class="list-unstyled clearfix">
          <li class="filter_by_size">
            <%= link_to potepan_category_path(size: size.presentation) do %>
              <%= size.presentation %><span>(<%= products_count_option(size.name) %>)</span>
            <% end %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>

app/views/potepan/categories/_filter_by_sort.html.erb
<div class="col-xs-6">
  <%= form_tag(potepan_category_path(@taxon.id), method: :get, enforce_utf8: false) do %>
  <%= select_tag(:sort, options_for_select([
    ["新着順", "NEW_PRODUCTS"],
    ["安い順", "LOW_PRICE"],
    ["高い順", "HIGH_PRICE"],
    ["古い順", "OLD_PRODUCTS"]],
    selected: params[:sort] || "NEW_PRODUCTS"),
    { id: "guiest_id1", class: "select-drop", onchange: "submit(this.form)"})%>
  <% end %>
</div>

app/views/potepan/categories/_light_section.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li><%= link_to "Home", potepan_index_path %></li>
          <li><a href="#">shop</a></li>
          <li class="active"><%= taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_product.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
  <%= link_to potepan_product_path(product.id) do %>
    <div class="productImage clearfix">
      <%= image_tag(product.display_image.attachment(:product)) %>
    </div>
    <div class="productCaption clearfix">
      <h5><%= product.name %></h5>
      <h3><%= product.display_price %></h3>
    </div>
  <% end %>
  </div>
</div>

app/views/potepan/home/_new_products.html.erb
<div class="slide">
  <%= link_to potepan_product_path(new_products.id) do %>
    <div class="productImage clearfix">
      <%= image_tag(new_products.display_image.attachment(:product)) %>
    </div>
    <div class="productCaption clearfix">
      <h5><%= new_products.name %></h5>
      <h3><%= new_products.display_price %></h3>
    </div>
  <% end %>
</div>

app/views/potepan/orders/_line_item.html.erb
<%= order_form.fields_for :line_items, line_item do |line_item_fields| %>
  <tr>
    <td class="col-xs-2">
      <%= link_to potepan_line_item_path(line_item), class: "close", method: :delete do %>
        <span aria-hidden="true">&times;</span>
      <% end %>
      <span class="cartImage">
        <%= image_tag(line_item.variant.display_image.attachment(:small)) %>
      </span>
    </td>
    <td class="col-xs-4"><%= line_item.name %></td>
    <td class="col-xs-2"><%= line_item.display_price %></td>
    <td class="col-xs-2"><%= line_item_fields.number_field :quantity, min: 0 %></td>
    <td class="col-xs-2"><%= line_item.display_total %></td>
  </tr>
<% end %>s

app/views/potepan/products/_cart_form.html.erb
<%= form_for :order, url: potepan_line_items_path do |f| %>
  <% if product.variants.any? %>
    <span class='quick-drop'>
      <%= select_tag :variant_id, options_from_collection_for_select(product.varients, :id, :options_text), class: "select-drop" %>
    </span>
  <% else %>
    <%= hidden_field_tag "variant_id", product.master.id %>
  <% end %>
  <span class="quick-drop resizeWidth">
    <%= select_tag :quantity, options_for_select([*1..5]), class: "select-drop" %>
  </span>
  <div class="btn-area">
    <%= button_tag(type: 'submit', class: 'btn btn-primary btn-block') do %>
      カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i>
    <% end %>
  </div>
<% end %>

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <% related_products.each do |related_product| %>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="productBox">
        <%= link_to potepan_product_path(related_product.id) do %>
          <div class="productImage clearfix">
            <%= image_tag(related_product.display_image.attachment(:product)) %>
            <div class="productCaption clearfix">
              <h5><%= related_product.name %></h5>
              <h3><%= related_product.display_price %></h3>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/products/search.html.erb
<% provide(:title, @search) %>
<div class="main-wrapper">
  <!-- LIGHT SECTION -->
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2><%= @search %></h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li>
              <%= link_to "Home", potepan_index_path %>
            </li>
            <li>
              <<%= link_to "shop", potepan_category_path(1) %>
            </li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix productsContent">
    <div class="container">
      <div class="row">
        <% @products.each do |product| %>
          <div class="col-sm-3 col-xs-12">
            <div class="productBox">
            <%= link_to potepan_product_path(product.id) do %>
              <div class="productImage clearfix">
                <%= image_tag(product.display_image.attachment(:large)) %>
              </div>
              <div class="productCaption clearfix">
                <h5><%= product.name %></h5>
                <h3><%= product.display_price %></h3>
              </div>
            <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
  <!-- Footer-logo  -->
  <%= render 'layouts/footer_logos_images'%>
</div>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<div class="main-wrapper">
  <!-- LIGHT SECTION -->
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2><%= @product.name %></h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li>
              <%= link_to "Home", potepan_index_path %>
            </li>
            <li class="active"><%= @product.name %></li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix">
    <div class="container">
      <div class="row singleProduct">
        <div class="col-xs-12">
          <div class="media">
            <div class="media-left productSlider">
              <div id="carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <% @product.images.each_with_index do |image, i| %>
                    <div class="item <%= "active" if i.zero? %>" data-thumb="<%= i %>">
                      <%= image_tag(image.attachment(:large)) %>
                    </div>
                  <% end %>
                </div>
              </div>
              <div class="clearfix">
                <div id="thumbcarousel" class="carousel slide" data-interval="false">
                  <div class="carousel-inner">
                    <% @product.images.each_with_index do |image, i| %>
                      <div data-target="#carousel" data-slide-to="<%= i %>" class="thumb">
                        <%= image_tag(image.attachment(:small)) %>
                      </div>
                    <% end %>
                  </div>
                  <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                  </a>
                  <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                  </a>
                </div>
              </div>
            </div>
            <div class="media-body">
              <ul class="list-inline">
                <%= link_to potepan_category_path(@product.taxons.first.id) do %>
                  <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
                <% end %>
                <li>
                  <a href="#"><i class="fa fa-plus" aria-hidden="true"></i>Share This</a>
                </li> 
              </ul>
              <h2><%= @product.name %></h2>
              <h3><%= @product.display_price %></h3>
              <p><%= @product.description %></p>
              <%= render "cart_form", product: @product %>
              <div class="tabArea">
                <ul class="nav nav-tabs">
                  <li class="active">
                    <a data-toggle="tab" href="#details">details</a>
                  </li>
                  <li>
                    <a data-toggle="tab" href="#about-art">about art</a>
                  </li>
                  <li>
                    <a data-toggle="tab" href="#sizing">sizing</a>
                  </li>
                  <li>
                    <a data-toggle="tab" href="#shipping">shipping</a>
                  </li>
                </ul>
                <div class="tab-content">
                  <div id="details" class="tab-pane fade in active">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                    <ul class="list-unstyled">
                      <li>Black, Crew Neck</li>
                      <li>75% Cotton, 25% Rayon</li>
                      <li>Waterbased Ink</li>
                      <li>Wash Cold, dry low</li>
                    </ul>
                  </div>
                  <div id="about-art" class="tab-pane fade">
                    <p>Nulla facilisi. Mauris efficitur, massa et iaculis accumsan, mauris velit ultrices purus, quis condimentum nibh dolor ut tortor. Donec egestas tortor quis mattis gravida. Ut efficitur elit vitae dignissim volutpat. </p>
                  </div>
                  <div id="sizing" class="tab-pane fade">
                    <p>Praesent dui felis, gravida a auctor at, facilisis commodo ipsum. Cras eu faucibus justo. Nullam varius cursus nisi, sed elementum sem sagittis at. Nulla tellus massa, vestibulum a commodo facilisis, pulvinar convallis nunc.</p>
                  </div>
                  <div id="shipping" class="tab-pane fade">
                    <p>Mauris lobortis augue ex, ut faucibus nisi mollis ac. Sed volutpat scelerisque ex ut ullamcorper. Cras at velit quis sapien dapibus laoreet a id odio. Sed sit amet accumsan ante, eu congue metus. Aenean eros tortor, cursus quis feugiat sed, vestibulum vel purus.</p>
                  </div>
                </div>
              </div> 
            </div>
          </div>
        </div>
      </div>
      <%= render 'related_products', related_products: @related_products %>
    </div>
  </section>
</div>